$(document).ready(function(){
  $('.slayder').slick({
      arrows:false,
      dots:true,
      adaptiveHeight:true,
      speed:1000,
      autoplay:true,    
      autoplaySpeed:3000,
      TouchTreashold:5,
      slidesToShow:1
  });
});